version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: ReactionsMongodb
    ports:
      - "27017:27017"
    networks:
      - app
  reactions-back:
    image: node:latest
    user: node
    container_name: ReactionsBack
    working_dir: "/app"
    environment:
      - CONTAINER=yes
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: "npm run start"
  nginx:
    image: nginx:latest
    container_name: ReactionsNginx
    depends_on:
      - reactions-back
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app
networks:
  app:
